"use client";

import { useState } from "react";
import { Download, Loader2 } from "lucide-react";
import { AnalysisResponse, ProjectInput } from "@/types";

interface Props {
    result: AnalysisResponse;
    projectInput: ProjectInput;
}

export function ExportButton({ result, projectInput }: Props) {
    const [loading, setLoading] = useState(false);

    async function handleExport() {
        setLoading(true);
        try {
            const { jsPDF } = await import("jspdf");
            const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

            const margin = 20;
            let y = margin;
            const pageWidth = 210;
            const contentWidth = pageWidth - margin * 2;

            // Helper: wrapped text
            function addText(text: string, fontSize: number, isBold = false, color: [number, number, number] = [220, 220, 240]) {
                doc.setFontSize(fontSize);
                doc.setFont("helvetica", isBold ? "bold" : "normal");
                doc.setTextColor(...color);
                const lines = doc.splitTextToSize(text, contentWidth);
                if (y + lines.length * (fontSize * 0.4) > 280) {
                    doc.addPage();
                    y = margin;
                }
                doc.text(lines, margin, y);
                y += lines.length * (fontSize * 0.45) + 2;
            }

            function addSpacer(h = 4) { y += h; }
            function addLine() {
                doc.setDrawColor(80, 60, 120);
                doc.line(margin, y, pageWidth - margin, y);
                y += 4;
            }

            // Background
            doc.setFillColor(14, 17, 32);
            doc.rect(0, 0, 210, 297, "F");

            // Title
            addText("CAMPUS-2-CASH", 22, true, [168, 85, 247]);
            addText("Project-to-Income Engine — Pitch Summary", 11, false, [150, 150, 180]);
            addText(`Generated: ${new Date().toLocaleDateString()}`, 9, false, [100, 100, 130]);
            addSpacer(6);
            addLine();

            // Project
            addText("PROJECT", 10, true, [168, 85, 247]);
            addText(projectInput.title, 16, true, [220, 220, 255]);
            if (projectInput.techStack.length > 0) {
                addText(`Stack: ${projectInput.techStack.join(", ")}`, 9, false, [150, 150, 180]);
            }
            addSpacer();
            addLine();

            // Evaluation
            addText("EVALUATION", 10, true, [168, 85, 247]);
            addText(`Real-World Value Score: ${result.evaluation.realWorldValueScore}/10 — ${result.evaluation.verdict}`, 13, true, [220, 220, 255]);
            addSpacer(2);

            const dims = Object.values(result.evaluation.dimensions);
            dims.forEach((d) => {
                addText(`${d.label}: ${d.score}/10 — ${d.summary}`, 9);
            });

            addSpacer(2);
            addText("Revenue Estimate (Year 1)", 10, true, [168, 85, 247]);
            const rev = result.evaluation.revenueEstimate;
            addText(`Conservative: ${rev.conservative}  |  Realistic: ${rev.realistic}  |  Optimistic: ${rev.optimistic}`, 9);
            addSpacer();
            addLine();

            // Monetization paths
            addText("MONETIZATION PATHS", 10, true, [168, 85, 247]);
            result.paths.forEach((path, i) => {
                addSpacer(2);
                addText(`${i + 1}. ${path.emoji} ${path.model} (${path.confidence} Confidence)`, 12, true, [220, 220, 255]);
                addText(`Target Users: ${path.targetUsers}`, 9, false, [150, 200, 180]);
                addText(`Pricing: ${path.pricing}`, 9);
                addText(`Why: ${path.whyItFits}`, 9);
                addText("Action Steps:", 9, true);
                path.steps.forEach((step, j) => {
                    addText(`  ${j + 1}. ${step}`, 9);
                });
            });

            addSpacer(6);
            addLine();
            addText("Overall Insights", 10, true, [168, 85, 247]);
            addText(result.overallInsights || result.evaluation.overallInsights, 9);

            addSpacer(6);
            addText("Generated by Campus-2-Cash · campus-2-cash.vercel.app · Vibe Hack 2026", 8, false, [80, 80, 100]);

            doc.save(`${projectInput.title.replace(/\s+/g, "-")}-pitch-summary.pdf`);
        } catch (e) {
            console.error("Export failed:", e);
        } finally {
            setLoading(false);
        }
    }

    return (
        <button
            onClick={handleExport}
            disabled={loading}
            className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-emerald-500/10 hover:bg-emerald-500/20 border border-emerald-500/20 text-emerald-400 hover:text-emerald-300 font-medium text-sm transition-all disabled:opacity-60"
        >
            {loading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
            Export PDF
        </button>
    );
}
